#! /bin/bash

# make phoneNumbers array
phoneNumbers=`cat contacts.json | jq -r '.[] | .phone'`
arr=($phoneNumbers)
# read messageBody
body=`cat messageBody`
echo "$body"
#send!
for phone in "${arr[@]}"
do
  echo "send to - " $phone
  osascript sendMessage.applescript "$phone" "$body"
done
